### ISSUE TITLE
manifest origin causes failed install

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/betachannel#38] opened 2014-06-19 17:53 UTC
```
I/Gecko   (  295): *************************
I/Gecko   (  295): A coding exception was thrown and uncaught in a Task.
I/Gecko   (  295):
I/Gecko   (  295): Full message: TypeError: undefined has no properties
I/Gecko   (  295): Full stack: this.DOMApplicationRegistry.startDownload<@resource://gre/modules/Webapps.jsm:1378:1
I/Gecko   (  295): TaskImpl_run@resource://gre/modules/Task.jsm:282:1
I/Gecko   (  295): resolve@resource://gre/modules/commonjs/sdk/core/promise.js:118:11
I/Gecko   (  295): then@resource://gre/modules/commonjs/sdk/core/promise.js:43:43
I/Gecko   (  295): resolve@resource://gre/modules/commonjs/sdk/core/promise.js:185:11
I/Gecko   (  295): reject@resource://gre/modules/commonjs/sdk/core/promise.js:133:24
I/Gecko   (  295): then@resource://gre/modules/commonjs/sdk/core/promise.js:52:51
I/Gecko   (  295): resolve@resource://gre/modules/commonjs/sdk/core/promise.js:185:11
I/Gecko   (  295): reject@resource://gre/modules/commonjs/sdk/core/promise.js:208:7
I/Gecko   (  295): TaskImpl_handleException@resource://gre/modules/Task.jsm:366:5
I/Gecko   (  295): TaskImpl_run@resource://gre/modules/Task.jsm:294:9
I/Gecko   (  295): Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:710:9
I/Gecko   (  295): this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:586:7
I/Gecko   (  295):
I/Gecko   (  295): *************************
```

**Comment by ozten** [comment] 2014-06-19 23:14
Install, download, "failed to install"

```
E/Profiler(  110): BPUnw: [1 total] thread_unregister_for_profiling(me=0xc61958)  (NOT REGISTERED) 
E/GeckoConsole(  110): [JavaScript Error: "Error while reading package:ReferenceError: app is not defined" {file: "resource://gre/modules/Webapps.jsm" line: 2909}]
E/GeckoConsole(  110): Content JS INFO at app://system.gaiamobile.org/js/app_install_manager.js:354 in ai_handleDownloadError: downloadError event, error code is INVALID_PACKAGE
```

**Comment by mykmelez** [comment] 2014-06-24 18:44
@nickdesaulniers do you have access to a package containing the build that is installed on your device? If so, can you extract the Webapps.jsm file from it (or point me at the build, so I can do that myself)?

Webapps.jsm is preprocessed, and some of the preprocessor directives are platform-specific, so it's hard to match line number references in the log to Webapps.jsm source file lines. But if I can access the version of the file in the build, so I can look at the actual line on which the exception is occurring, then I may be able to diagnose the problem.

@ozten: it looks like you're experiencing a different problem, although perhaps they're related. Either way, the same question applies to you as well!

**Comment by ozten** [comment] 2014-06-24 21:12
I've successfully installed 10 packaged apps. I've hit 2 new, unrelated bugs. I have not reproduced this install bug on any other packaged apps, so far.

<strike>Nick's package.zip</strike>

[Work log with links](https://etherpad.mozilla.org/betafox-testing)

I'll try removing various fields from the package manifest, such as precompile, to see if they are the root cause.

**Comment by ozten** [comment] 2014-06-24 21:35
I believe the root cause is the `origin` field in the package's manifest.

If I remove `"origin": "app://example.com",` and re-upload, the app is installable.

Should I just filter out origins?

**Comment by nickdesaulniers** [comment] 2014-06-24 21:54
But then if the app needs to have it's origin modified in client side JavaScript, won't that mess up the app?

**Comment by ozten** [comment] 2014-06-24 21:58
Good point, I guess we need to [support origin](https://developer.mozilla.org/en-US/Apps/Build/Manifest#origin).

I guess there is a platform bug at work here? Or what does the BetaFox install page need to do, so that origin works? -- clueless server side guy

**Comment by ozten** [comment] 2014-06-25 18:14
Reproduced with Jongla IM
has origin and fails http://d2gk.co/app/v/47/install/shout%40ozten.com%2CJongla%20IM
no origin, install fine http://d2gk.co/app/v/56/install/shout%40ozten.com%2CJongla%20IM

**Comment by ozten** [comment] 2014-06-25 21:18
Filed FxOS Runtime [bug#1030356](https://bugzilla.mozilla.org/show_bug.cgi?id=1030356)

**Comment by ozten** [comment] 2014-07-17 17:16
Please use the latest version of 1.3. Bug#1030356 was marked as a duplicate of a bug that has already been fixed. This explains why it worked on some phones and not others.

thanks!

**Closed as completed by ozten** 2014-07-17 17:16 UTC
Labels: bugzilla
